name: Deploy to production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-16.04
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/allstarsgame

            git status
            git pull https://fmedeiros95:${{ secrets.TOKEN }}@github.com/fmedeiros95/allstarsgame.git main

            pm2 delete aasg-alerts
            pm2 delete aasg-chat

            pm2 start /var/www/allstarsgame/servers/highlights/index.js --name aasg-alerts
            pm2 start /var/www/allstarsgame/servers/chat/index.js --name aasg-chat